on:
  push:
    branches:
      - '**'

name: Check Code Quality

jobs:
  code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.8.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.8.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit (on production dependencies)
        run: npm audit --production

      - name: Lint
        run: npm run lint
